# Generated by Django 3.2.18 on 2023-10-20 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=256, verbose_name='タイトル')),
                ('post_overview', models.TextField(null=True, verbose_name='概要')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='掲載開始')),
                ('ended_at', models.DateTimeField(verbose_name='掲載終了')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='board.board')),
            ],
        ),
    ]
