# Generated by Django 3.2.18 on 2023-10-27 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_post_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='写真'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_upload',
            field=models.FileField(blank=True, null=True, upload_to='file/%y/%m/%d', verbose_name='ファイル'),
        ),
    ]
