# Generated by Django 3.2.18 on 2023-11-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20231027_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='board_img',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='デフォルト画像'),
        ),
    ]
